### ISSUE TITLE
排版需要再优化优化

### ISSUE THREAD

**Issue by PureSincere** [teamonn/interview-guide-for-FEE#10]
如题，排版需要再优化优化，建议参考阮一峰的中文技术文档的写作规范：https://github.com/ruanyf/document-style-guide/tree/master

**Comment by teamonn** [comment]
奈斯👍🏻已处理

**Comment by PureSincere** [comment]
有瑕疵

**Comment by PureSincere** [comment]
分支 https://github.com/PureSincere/interview-guide-for-FEE/tree/resolve-issue-%2310 已解决
